trigger:
- master

variables:
  sourceDirectory: '$(System.DefaultWorkingDirectory)'
  buildDirectory: '$(sourceDirectory)/public'

pool:
  vmImage: ubuntu-latest

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '16.15.1'
  displayName: 'Install Node.js'

- script: |
    npm install
    npm run build
  displayName: 'npm install and build'

- task: CopyFiles@2
  inputs:
    SourceFolder: '$(sourceDirectory)'
    Contents: '.htaccess'
    TargetFolder: '$(buildDirectory)'
    
- task: ArchiveFiles@2
  inputs:
    rootFolderOrFile: '$(buildDirectory)'
    includeRootFolder: true
    archiveType: 'zip'
    archiveFile: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'
    replaceExistingArchive: true
- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'
    publishLocation: 'Container'